name: Trigger Deployment

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trigger Deployment via GET Request
        run: |
          curl -X GET your-render-webhook-url-here
