name: Main workflow

on: [push]

jobs:
  tests:
    name:  run tests 
    uses : ./.github/workflows/ci-test.yml

  deploy:
    name : deploy to render host
    needs: tests
    uses : ./.github/workflows/cd-render.yml
  